name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: "main"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: tstackhouse/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: ""
          repositories_forks: true
          plugin_languages: yes
